//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusFleaMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsComments
    {
        public int GC_ID { get; set; }
        public Nullable<int> GC_User { get; set; }
        public string GC_Content { get; set; }
        public Nullable<double> GC_Point { get; set; }
        public Nullable<int> GC_Good { get; set; }
        public Nullable<System.DateTime> GC_Date { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Users Users { get; set; }
    }
}
