//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusFleaMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public Goods()
        {
            this.ShopRecords = new HashSet<ShopRecords>();
            this.GoodsComments = new HashSet<GoodsComments>();
        }
    
        public int G_ID { get; set; }
        public string G_Name { get; set; }
        public Nullable<int> G_Category { get; set; }
        public string G_Description { get; set; }
        public Nullable<int> G_User { get; set; }
        public Nullable<decimal> G_Price { get; set; }
        public Nullable<int> G_Inventory { get; set; }
        public Nullable<System.DateTime> G_Date { get; set; }
        public Nullable<int> G_SalesVolume { get; set; }
        public string G_State { get; set; }
    
        public virtual CategoryOfGoods CategoryOfGoods { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<ShopRecords> ShopRecords { get; set; }
        public virtual ICollection<GoodsComments> GoodsComments { get; set; }
    }
}
