//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusFleaMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageComments
    {
        public int MC_ID { get; set; }
        public Nullable<System.DateTime> MC_Date { get; set; }
        public string MC_Content { get; set; }
        public Nullable<int> MC_User { get; set; }
        public Nullable<int> MC_Message { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual Users Users { get; set; }
    }
}
