//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusFleaMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopRecords
    {
        public int SR_ID { get; set; }
        public string SR_RecordNumber { get; set; }
        public Nullable<int> SR_User { get; set; }
        public Nullable<int> SR_Good { get; set; }
        public Nullable<int> SR_GoodCount { get; set; }
        public Nullable<System.DateTime> SR_OrderDate { get; set; }
        public string SR_PayType { get; set; }
        public string SR_Address { get; set; }
        public Nullable<decimal> SR_Money { get; set; }
        public Nullable<System.DateTime> SR_ConfirmDate { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Users Users { get; set; }
    }
}
