//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusFleaMarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Goods = new HashSet<Goods>();
            this.GoodsComments = new HashSet<GoodsComments>();
            this.MessageComments = new HashSet<MessageComments>();
            this.Messages = new HashSet<Messages>();
            this.ShopRecords = new HashSet<ShopRecords>();
        }
    
        public int U_ID { get; set; }
        public string U_StuNumber { get; set; }
        public string U_Name { get; set; }
        public string U_Passward { get; set; }
        public string U_Phone { get; set; }
        public string U_HeadImage { get; set; }
        public string U_CompusCard { get; set; }
        public string U_State { get; set; }
    
        public virtual ICollection<Goods> Goods { get; set; }
        public virtual ICollection<GoodsComments> GoodsComments { get; set; }
        public virtual ICollection<MessageComments> MessageComments { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<ShopRecords> ShopRecords { get; set; }
    }
}
